[package]
name = "rust_counter_mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
rmcp = { version = "0.3", features = ["transport-io"] }

